#############################################################################
# Configuration section
#############################################################################

##############################################################################
# Top rules using dune
##############################################################################

all::
	dune build
clean::
	dune clean
# Only the cmm package: the workspace also contains caps and the
# semgrep-pfff-libs packages, which come from submodules and are none of our
# business to install into someone's switch.
#
# This installs the qc binary and, via runtime/dune, the run-time system's
# headers, linker script and sources into <prefix>/lib/cmm. "make uninstall"
# reverses both.
install::
	dune install cmm

uninstall::
	dune uninstall cmm
# Two tiers, because they have very different requirements.
#
# "test" is the cheap one: does qc still translate every C-- file we have?
# It needs nothing but qc, runs in seconds, and is the one to run while
# working on the compiler.
#
# "test-tiger", "test-rt", "test-quest", "test-native" and "test-lcc"
# validate code generation rather than just the absence of crashes: they
# build and run real programs and check their output and exit code. All
# five need the i386 cross toolchain and qemu binfmt (see demos/Makefile
# for the requirements), so they are kept separate. test-rt covers what
# test-tiger cannot (`cut to`, `foreign "C-- thread"`, stack unwinding);
# test-quest is pure calling-convention ABI tests, qc-- linked against gcc
# in both directions (tests/quest.tests, ported from TODO/tests/quest);
# test-native is the general regression suite (tests/native.tests, ported
# from arch/all.x86.tst); test-lcc is LCC's own regression suite translated
# to C-- (tests/lcc.tests, ported from lcc.x86.tst).
#
# All eight compare against a recorded baseline rather than demanding that
# everything pass, since a third of tests/src consists of negative tests
# and there are known failures in the others (see tests/rt.tests,
# tests/quest.tests, tests/native.tests, tests/lcc.tests and
# tests/tiger.tests). Re-record with the scripts' --update flag, and review
# the diff when you do.
test::
	tests/run-compile.sh

test-tiger::
	tests/run-tiger.sh

# claude: self-contained the same way test-tiger is - tests/tiger/
# tigermain-ppc.o and stdlib-ppc.a are checked in, regenerated by hand with
# tests/tiger/regenerate-ppc.sh (needs a fork-tiger checkout; run-tiger-ppc.sh
# itself does not). No TIMEOUT override here unlike test-native-ppc: nothing
# in this suite currently hangs, only compiles/links/runs wrong - if that
# changes, apply the same fix.
test-tiger-ppc::
	tests/run-tiger-ppc.sh

# claude: self-contained the same way test-tiger/test-tiger-ppc are -
# tests/tiger/tigermain-riscv32.o and stdlib-riscv32.a are checked in,
# regenerated by hand with tests/tiger/regenerate-riscv32.sh (needs a
# fork-tiger checkout; run-tiger-riscv32.sh itself does not, but DOES need
# the riscv32 bare-metal toolchain - see that script's own comment). Reaches
# 15/15, same bar as ppc (see docs/claude_notes/notes_riscv.txt) - unlike
# mips/sparc/arm's own run-tiger-*.sh (1/15, 1/15, 6/15), which stay off
# this list. No TIMEOUT override, matching test-tiger-ppc: nothing in this
# suite hangs.
test-tiger-riscv32::
	tests/run-tiger-riscv32.sh

test-rt::
	tests/run-rt.sh

# claude: calling-convention ABI tests, ported from TODO/tests/quest (see
# tests/quest.tests's header). Same i386/qemu requirement as test-tiger and
# test-rt, but needs no runtime library - pure argument/return-value
# passing between qc-- and gcc, in both directions.
test-quest::
	tests/run-quest.sh

test-native::
	tests/run-native.sh

# claude: ppc is newer and has more known failures than x86, including a
# few genuine hangs (not crashes) rather than fast wrong-answers, from
# bugs not yet root-caused. TIMEOUT=1 keeps test-all bounded regardless -
# a passing test finishes in well under a second, so 1s is generous
# margin, not a tight race (verified: same pass/fail set as the default
# 60s timeout). Run "BACKEND=ppc tests/run-native.sh" by hand (default
# TIMEOUT=60) when actually chasing one of those hangs, so a
# slow-but-legitimate run isn't cut off before it would finish anyway.
test-native-ppc::
	BACKEND=ppc TIMEOUT=1 tests/run-native.sh

# claude: OPT=3 counterparts of test-native/test-native-ppc - added after
# discovering that no suite in this list ever passed -O3, so a whole
# opt_level's worth of passes went completely unexercised by the
# regression corpus (that's how regalloc/colorgraph.ml's hang on this
# very suite's add.c-- went unnoticed - see arch/x86/x86backend.ml's
# optimizer). TIMEOUT=15 here (vs test-native's default 60s): generous
# enough not to cut off a slow-but-legitimate pass, tight enough that a
# real hang doesn't make test-all slow - tighten further only after
# confirming, the way test-native-ppc's own comment did for TIMEOUT=1,
# that it doesn't change the pass/fail set. TIMEOUT=1 for ppc, matching
# test-native-ppc exactly (same reasoning, same already-known hangs).
test-native-o3::
	OPT=3 TIMEOUT=15 tests/run-native.sh

test-native-ppc-o3::
	OPT=3 BACKEND=ppc TIMEOUT=1 tests/run-native.sh

test-lcc::
	tests/run-lcc.sh

test-optimizer::
	tests/run-optimizer.sh

test-phases::
	tests/run-phases.sh

test-all:: test test-tiger test-tiger-ppc test-tiger-riscv32 test-rt test-quest test-native test-native-ppc test-native-o3 test-native-ppc-o3 test-lcc test-optimizer test-phases
build-docker:
	docker build -t "cmm" .

##############################################################################
# Variables
##############################################################################
TOP=$(shell pwd)

SRC= this.ml driver.ml main.ml

TARGET=qc

SYSLIBS=nums.cma bigarray.cma str.cma unix.cma

LIBS= commons/commons.cma \
     commons2/lib.cma \
     error/lib.cma \
     commons3/lib.cma \
     h_asdl/lib.cma \
     parsing/lib.cma \
     front_rtl/lib.cma \
     front_asm/lib.cma \
     front_fenv/lib.cma \
     front_cfg/lib.cma \
     front_nelab/lib.cma \
     front_target/lib.cma \
     front_zipcfg/lib.cma \
     front_ir/lib.cma \
     assembler/lib.cma \
     front_last/lib.cma \
     h_camlburg/engine/lib.cma \
     arch/ppc/lib.cma \
     arch/x86/lib.cma \
     arch/interpreter/lib.cma \
     arch/dummy/lib.cma \

# note that front_nelab and front_cfg are independent so could compile
# then in parallel
MAKESUBDIRS= \
   commons \
   commons2 \
   error \
   commons3 \
   h_asdl \
   h_camlburg \
   parsing \
   front_rtl \
   front_asm  front_fenv \
   front_cfg  front_zipcfg \
   front_nelab \
   front_target \
   front_ir \
   assembler \
   front_last \
   arch/interpreter \
   arch/ppc \
   arch/x86 \
   arch/dummy \


#  tools \
#  rtl compiler runtime \
#  interpreter \

INCLUDEDIRS=$(MAKESUBDIRS) 

#commons/lib-sexp

##############################################################################
# Generic variables
##############################################################################
-include $(TOP)/Makefile.common

##############################################################################
# Top rules
##############################################################################
.PHONY:: all all.opt opt top clean distclean

allold:: 
	$(MAKE) rec 
	$(MAKE) $(TARGET) 

optold:
	$(MAKE) rec.opt 
	$(MAKE) $(TARGET).opt

all.opt: opt
top: $(TARGET).top


rec:
	set -e; for i in $(MAKESUBDIRS); do $(MAKE) -C $$i all || exit 1; done 

rec.opt:
	set -e; for i in $(MAKESUBDIRS); do $(MAKE) -C $$i all.opt || exit 1; done 


$(TARGET): $(LIBS) $(OBJS)
	$(OCAMLC) $(BYTECODE_STATIC) -o $@ $(SYSLIBS) $^

$(TARGET).opt: $(LIBS:.cma=.cmxa) $(OPTOBJS) 
	$(OCAMLOPT) $(STATIC) -o $@ $(SYSLIBS:.cma=.cmxa)  $^


$(TARGET).top: $(LIBS) $(OBJS) 
	$(OCAMLMKTOP) -o $@ $(SYSLIBS) $^


this.ml: this.in
	cp this.in this.ml


cleanold::
	rm -f $(TARGET)
cleanold:: 
	rm -f $(TARGET).top
cleanold::
	set -e; for i in $(MAKESUBDIRS); do $(MAKE) -C $$i clean; done 

depend::
	set -e; for i in $(MAKESUBDIRS); do $(MAKE) -C $$i depend; done


# add -custom so dont need add e.g. ocamlbdb/ in LD_LIBRARY_PATH
CUSTOM=-custom

static:
	rm -f $(EXEC).opt $(EXEC)
	$(MAKE) STATIC="-ccopt -static" $(EXEC).opt
	cp $(EXEC).opt $(EXEC)

purebytecode:
	rm -f $(EXEC).opt $(EXEC)
	$(MAKE) BYTECODE_STATIC="" $(EXEC)


distclean:: clean
	set -e; for i in $(MAKESUBDIRS); do $(MAKE) -C $$i $@; done
	rm -f Makefile.config

##############################################################################
# Build documentation
##############################################################################
.PHONY:: docs

##############################################################################
# Install
##############################################################################

##############################################################################
# Developer rules
##############################################################################

DIRS= $(filter-out commons commons2 error, $(MAKESUBDIRS))
# you want "-dot-reduce"
# don't put "-dot-colors white"; using colors ocamldoc generates one
#  color per directory ! quite useful
# todo? generate a graph using the  -dot-types flag ? (type dependencies)
dotall:
	ocamldoc $(INCLUDES) $(DIRS:=/*.ml) $(SRC)  -dot -dot-reduce 
	perl -p -i -e 's/\[style=filled, color=white\]//;' ocamldoc.out
	dot -Tps ocamldoc.out > dot.ps
	mv dot.ps Fig_graph_ml.ps
	ps2pdf Fig_graph_ml.ps
	rm -f Fig_graph_ml.ps

tags:
	~/pfff/stags -verbose -lang ml .
graph:
	~/pfff/codegraph.opt -derived_data -lang cmt -build .
visual:
	codemap . -no_legend -screen_size 2 # # -filter pfff .

##############################################################################
# Literate Programming rules
##############################################################################
# now in docs/literate/mkfile
