##############################################################################
# Top rules using dune
##############################################################################

# claude: written by ./configure - the cross toolchain/qemu settings for
# the optional "make test-<arch>*" tiers below (see that script's own
# comments). Its "export VAR=value" lines both set and re-export each
# variable, so a script like tests/run-tiger-ppc.sh sees the same CCPPC/
# RUN_PPC a plain "tests/run-tiger-ppc.sh" invocation would if configure
# was never run: absent -> falls back to that script's own default. "-"
# rather than plain "include": don't fail if configure hasn't been run
# yet, since "dune build" itself needs none of this.
-include Makefile.config

all::
	dune build
clean::
	dune clean
# Only the cmm package: the workspace also contains caps and the
# semgrep-pfff-libs packages, which come from submodules and are none of our
# business to install into someone's switch.
#
# This installs the qc binary and, via runtime/dune, the run-time system's
# headers, linker script and sources into <prefix>/lib/cmm. "make uninstall"
# reverses both.
install::
	dune install cmm

uninstall::
	dune uninstall cmm
# Two tiers, because they have very different requirements.
#
# "test" is the cheap one: does qc still translate every C-- file we have?
# It needs nothing but qc, runs in seconds, and is the one to run while
# working on the compiler.
#
# "test-tiger", "test-rt", "test-quest", "test-native" and "test-lcc"
# validate code generation rather than just the absence of crashes: they
# build and run real programs and check their output and exit code. All
# five need the i386 cross toolchain and qemu binfmt (see demos/Makefile
# for the requirements), so they are kept separate. test-rt covers what
# test-tiger cannot (`cut to`, `foreign "C-- thread"`, stack unwinding);
# test-quest is pure calling-convention ABI tests, qc-- linked against gcc
# in both directions (tests/quest.tests, ported from TODO/tests/quest);
# test-native is the general regression suite (tests/native.tests, ported
# from arch/all.x86.tst); test-lcc is LCC's own regression suite translated
# to C-- (tests/lcc.tests, ported from lcc.x86.tst).
#
# All eight compare against a recorded baseline rather than demanding that
# everything pass, since a third of tests/src consists of negative tests
# and there are known failures in the others (see tests/rt.tests,
# tests/quest.tests, tests/native.tests, tests/lcc.tests and
# tests/tiger.tests). Re-record with the scripts' --update flag, and review
# the diff when you do.
test::
	tests/run-compile.sh

test-tiger::
	tests/run-tiger-x86.sh

# claude: self-contained the same way test-tiger is - tests/tiger/
# tigermain-ppc.o and stdlib-ppc.a are checked in, regenerated by hand with
# tests/tiger/regenerate-ppc.sh (needs a fork-tiger checkout; run-tiger-ppc.sh
# itself does not). No TIMEOUT override here unlike test-native-ppc: nothing
# in this suite currently hangs, only compiles/links/runs wrong - if that
# changes, apply the same fix.
test-tiger-ppc::
	tests/run-tiger-ppc.sh

# claude: self-contained the same way test-tiger/test-tiger-ppc are -
# tests/tiger/tigermain-riscv32.o and stdlib-riscv32.a are checked in,
# regenerated by hand with tests/tiger/regenerate-riscv32.sh (needs a
# fork-tiger checkout; run-tiger-riscv32.sh itself does not, but DOES need
# the riscv32 bare-metal toolchain - see that script's own comment). Reaches
# 15/15, same bar as ppc (see docs/claude_notes/notes_riscv.txt) - unlike
# mips/sparc/arm's own run-tiger-*.sh (1/15, 1/15, 6/15), which stay off
# this list. No TIMEOUT override, matching test-tiger-ppc: nothing in this
# suite hangs.
test-tiger-riscv32::
	tests/run-tiger-riscv32.sh

# claude: self-contained the same way test-tiger/test-tiger-ppc/
# test-tiger-riscv32 are - tests/tiger/tigermain-m68k.o and stdlib-m68k.a
# are checked in, regenerated by hand with tests/tiger/regenerate-m68k.sh
# (needs a fork-tiger checkout; run-tiger-m68k.sh itself does not, but DOES
# need the m68k cross toolchain - gcc-m68k-linux-gnu/libc6-dev-m68k-cross,
# not installed on this machine by default). Reaches 15/15 on the first
# real attempt, same bar as ppc/riscv32/mips (see docs/claude_notes/
# notes_m68k.txt) - unlike sparc/arm's own run-tiger-*.sh, which stay off
# this bar. No TIMEOUT override: nothing in this suite hangs.
test-tiger-m68k::
	tests/run-tiger-m68k.sh

# claude: self-contained the same way test-tiger-ppc/test-tiger-riscv32 are -
# tests/tiger/tigermain-mips.o and stdlib-mips.a are checked in, regenerated
# by hand with tests/tiger/regenerate-mips.sh (needs a fork-tiger checkout;
# run-tiger-mips.sh itself only needs the mipsel cross toolchain + qemu-mipsel).
# Reaches 15/15, same bar as ppc/riscv32 (see mips-backend-status notes) -
# the last fix was a runtime.c pc-adjustment bug (a MIPS call site's own
# pcmap-table label lands 4 bytes before where $31/ra actually points after
# a real "jal", breaking every GC-triggering frame walk; compensated for in
# normal_change, mirroring the analogous sparc fix a few lines above it).
test-tiger-mips::
	tests/run-tiger-mips.sh

# claude: the sparc counterpart of test-tiger-mips just above - same
# self-contained shape and same reasoning for being included at a low bar.
# Only 1/15 (sieve, not hello - see tests/expected/tiger-sparc.txt).
test-tiger-sparc::
	tests/run-tiger-sparc.sh

# claude: the arm (32-bit) counterpart of test-tiger-mips/test-tiger-sparc
# above - same self-contained shape and same reasoning for being included
# at a low bar. 11/15 - the best of the three low-bar backends, but still
# short of the 15/15 ppc/riscv32 clear (see tests/expected/tiger-arm.txt).
test-tiger-arm::
	tests/run-tiger-arm.sh

# claude: the bits64 counterpart of test-tiger - tests/tiger64/ instead of
# tests/tiger/, see tests/tiger64/README. Self-contained the same way:
# tigermain-riscv64.o/stdlib-riscv64.a are checked in, regenerated by hand
# with tests/tiger64/regenerate-riscv64.sh (needs a fork-tiger checkout;
# run-tiger64-riscv64.sh itself does not, but DOES need the riscv64 cross
# toolchain). 13/15, not the 15/15 bar test-tiger/test-tiger-ppc/
# test-tiger-riscv32 clear - two real, separately root-caused bugs remain
# (a GC-triggered heap corruption on colmajor, and a wrong exit code on
# merge with otherwise-correct stdout - see tests/tiger64/README). Still
# in test-all below: like every other tier here, this compares against a
# recorded baseline (expected/tiger64-riscv64.txt) rather than demanding
# 100%, so it still catches regressions same as the rest.
test-tiger64-riscv64::
	tests/run-tiger64-riscv64.sh

# claude: the -alpha counterpart of test-tiger64-riscv64 just above - same
# self-contained shape (tigermain-alpha.o/stdlib-alpha.a checked in,
# regenerate-alpha.sh needs fork-tiger, run-tiger64-alpha.sh itself only
# needs the alpha cross toolchain). 12/15 - only colmajor/merge/sieve
# fail, all for the same reason (real integer division: alpha has no
# hardware divide instruction at all, unlike riscv64's RV64M "div" -
# needs a call to libgcc's __divq helper, not yet implemented, see
# tests/tiger64/README).
test-tiger64-alpha::
	tests/run-tiger64-alpha.sh

# claude: the -arm64 (Linux/ELF, the bare/default flag of the arm64 pair -
# see driver/main.ml's use_arm64 comment) counterpart of test-tiger64-riscv64
# above - same self-contained shape (tigermain-arm64.o/stdlib-arm64.a checked
# in - bare names, matching -arm64 itself being the bare/default flag; the
# Mach-O tier below now carries the explicit "-mach-o" suffix on its own
# artefacts instead, freeing these up - regenerate-arm64.sh needs fork-tiger,
# run-tiger64-arm64.sh itself needs the arm64 cross toolchain, though on this
# repo's own aarch64-linux dev host that toolchain IS the native one, same as
# x86 on an x86 host). 13/15, matching test-tiger64-riscv64/
# test-tiger64-arm64-mach-o's own bar exactly, with the SAME two failures
# (colmajor's GC-triggered heap corruption; merge's wrong exit code with
# otherwise-correct stdout) - see docs/claude_notes/notes_arm64.txt's own
# follow-up section for why neither is arm64-specific. Unlike the Mach-O tier
# below, this one is NOT Darwin-gated: it is the whole point of this tier
# (verified end to end from fork-tiger per the "runtime: split
# arm64cont.s/amd64cont.s" commit), so it always runs in test-all - the
# arm64/amd64 cross toolchains are already a test-all prerequisite via
# test-tiger64-riscv64's own sibling requirements.
test-tiger64-arm64::
	tests/run-tiger64-arm64.sh

# claude: the -amd64 (Linux/ELF) counterpart of test-tiger64-arm64 above -
# same self-contained shape (tigermain-amd64.o/stdlib-amd64.a checked in -
# bare names, same reasoning as test-tiger64-arm64's own - regenerate-amd64.sh
# needs fork-tiger, run-tiger64-amd64.sh itself needs the amd64 cross
# toolchain plus qemu-x86_64 to run the result on this repo's own
# aarch64-linux dev host). 9/15, NOT the 13/15 bar test-tiger64-arm64 clears -
# colmajor and merge fail for the SAME already-documented cross-backend
# reasons those two do everywhere else, but rc4/rb/wf/wff also fail here,
# matching test-tiger64-amd64-mach-o's own exact 9/15 bar and failure set
# (see that target's own comment and docs/claude_notes/notes_amd64.txt's
# follow-up section for the diagnosis). Not Darwin-gated, same reasoning as
# test-tiger64-arm64 above.
test-tiger64-amd64::
	tests/run-tiger64-amd64.sh

# claude: the -arm64-mach-o counterpart of test-tiger64-riscv64 above -
# same self-contained shape (tigermain-arm64-mach-o.o/stdlib-arm64-mach-o.a
# checked in - "-mach-o" suffix: plain "arm64" is now claimed by the
# Linux/ELF tigermain-arm64.o/stdlib-arm64.a test-tiger64-arm64 above uses,
# since -arm64 itself is the bare/default flag of the pair -
# regenerate-arm64-mach-o.sh needs fork-tiger, run-tiger64-arm64-mach-o.sh itself
# needs no cross toolchain at all - this machine's own native architecture,
# on an Apple Silicon Mac). 13/15, matching riscv64's own bar exactly, with
# the SAME two failures (colmajor's GC-triggered heap corruption; merge's
# wrong exit code with otherwise-correct stdout) - see
# docs/claude_notes/notes_arm64.txt's own follow-up section for why
# neither is arm64-specific. Darwin-only (see -arm64-mach-o's own comment
# in driver/main.ml) - test-all below now only pulls this tier in when
# ./configure detected Darwin (CCARM64MACHO set in Makefile.config), so a
# plain "make test-all" on Linux no longer fails outright for lack of an
# ld64/Mach-O linker; run "make test-tiger64-arm64-mach-o" directly to
# force it anyway (still fails on Linux, same reason).
test-tiger64-arm64-mach-o::
	tests/run-tiger64-arm64-mach-o.sh

# claude: the -amd64-mach-o counterpart of test-tiger64-arm64-mach-o above -
# same self-contained shape (tigermain-amd64-mach-o.o/stdlib-amd64-mach-o.a
# checked in - "-mach-o" suffix, same reasoning as test-tiger64-arm64-mach-o's
# own - regenerate-amd64-mach-o.sh needs fork-tiger, run-tiger64-amd64-mach-o.sh itself
# needs the explicit "-arch x86_64" cross-target flag but no separate cross
# toolchain/qemu - clang cross-assembles/links directly on this host,
# output runs under Rosetta 2). 9/15, NOT the 13/15 bar test-tiger64-
# riscv64/test-tiger64-arm64-mach-o clear - colmajor and merge fail for the
# SAME already-documented cross-backend reasons those two do everywhere
# else (see tests/tiger64/README / docs/claude_notes/notes_arm64.txt's own
# follow-up section), but four more (rc4, rb, wf, wff) fail here that pass
# on arm64/riscv64. Not root-caused to a specific amd64-only bug: rb fails
# on tiger64/rb.c-- run against the LARGER wf.0 input but PASSES (as
# "rbshort") on the same source against the smaller rbshort.0 input, the
# same input-size/GC-pressure-sensitive shape already documented and NOT
# yet fixed for colmajor on every backend - see docs/claude_notes/
# notes_amd64.txt's own follow-up section for the full diagnosis and what
# was actually fixed to get from 0/15 (division did not even compile) to
# this baseline (a real, general amd64 register-allocation correctness bug
# in Post.binop, described there in detail). This compares against a
# recorded baseline (expected/tiger64-amd64-mach-o.txt) rather than
# demanding 100%, so it still catches regressions same as the rest.
# Darwin-only, same conditional test-all inclusion as test-tiger64-arm64-mach-o above.
test-tiger64-amd64-mach-o::
	tests/run-tiger64-amd64-mach-o.sh

# claude: regression test for a real amd64-only bug (see arch/amd64/
# amd64backend.ml's own retaddr_block comment and tests/run-amd64-
# alignment.sh's own header) - real x86-64 "call" pushes an 8-byte return
# address that the shared stack-frame layout didn't account for, so every
# call site was misaligned; glibc's printf crashed on it under real qemu-
# x86_64 even though it compiled and linked cleanly. Not baseline-driven
# like every other tier here: both its fixtures are expected to PASS,
# always - this is a "does the fix still hold" check, not a "how close to
# 100%" one.
test-amd64-alignment::
	tests/run-amd64-alignment.sh

test-rt::
	tests/run-rt.sh

# claude: calling-convention ABI tests, ported from TODO/tests/quest (see
# tests/quest.tests's header). Same i386/qemu requirement as test-tiger and
# test-rt, but needs no runtime library - pure argument/return-value
# passing between qc-- and gcc, in both directions.
test-quest::
	tests/run-quest.sh

test-native::
	tests/run-native.sh

# claude: ppc is newer and has more known failures than x86, including a
# few genuine hangs (not crashes) rather than fast wrong-answers, from
# bugs not yet root-caused. TIMEOUT=1 keeps test-all bounded regardless -
# a passing test finishes in well under a second, so 1s is generous
# margin, not a tight race (verified: same pass/fail set as the default
# 60s timeout). Run "BACKEND=ppc tests/run-native.sh" by hand (default
# TIMEOUT=60) when actually chasing one of those hangs, so a
# slow-but-legitimate run isn't cut off before it would finish anyway.
test-native-ppc::
	BACKEND=ppc TIMEOUT=1 tests/run-native.sh

# claude: OPT=3 counterparts of test-native/test-native-ppc - added after
# discovering that no suite in this list ever passed -O3, so a whole
# opt_level's worth of passes went completely unexercised by the
# regression corpus (that's how regalloc/colorgraph.ml's hang on this
# very suite's add.c-- went unnoticed - see arch/x86/x86backend.ml's
# optimizer). TIMEOUT=15 here (vs test-native's default 60s): generous
# enough not to cut off a slow-but-legitimate pass, tight enough that a
# real hang doesn't make test-all slow - tighten further only after
# confirming, the way test-native-ppc's own comment did for TIMEOUT=1,
# that it doesn't change the pass/fail set. TIMEOUT=1 for ppc, matching
# test-native-ppc exactly (same reasoning, same already-known hangs).
test-native-o3::
	OPT=3 TIMEOUT=15 tests/run-native.sh

test-native-ppc-o3::
	OPT=3 BACKEND=ppc TIMEOUT=1 tests/run-native.sh

test-lcc::
	tests/run-lcc.sh

test-optimizer::
	tests/run-optimizer.sh

test-phases::
	tests/run-phases.sh

# claude: the two Mach-O tiers above are Darwin-only (see their own
# comments) - CCARM64MACHO/CCAMD64MACHO are only "export"ed into
# Makefile.config by ./configure when "uname -s" = Darwin (see configure's
# "Write Makefile.config" section), so gating test-all on them here means
# it self-adapts to the host instead of unconditionally trying (and
# failing outright, no ld64/Mach-O linker) on Linux. Requires
# "./configure" to have run first (undocumented -include Makefile.config
# below is a no-op otherwise, same as every other CC*/RUN_* var here) -
# without it these two tiers are skipped even on a real Mac, consistent
# with every other optional backend in this list already needing
# configure's detection to be exercised at all.
ifdef CCARM64MACHO
TEST_ARM64_MACHO := test-tiger64-arm64-mach-o
endif
ifdef CCAMD64MACHO
TEST_AMD64_MACHO := test-tiger64-amd64-mach-o
endif

test-all:: test test-tiger test-tiger-ppc test-tiger-riscv32 test-tiger-mips test-tiger-sparc test-tiger-arm test-tiger64-riscv64 test-tiger64-alpha test-tiger64-arm64 test-tiger64-amd64 $(TEST_ARM64_MACHO) $(TEST_AMD64_MACHO) test-amd64-alignment test-rt test-quest test-native test-native-ppc test-native-o3 test-native-ppc-o3 test-lcc test-optimizer test-phases

# claude: subset of test-all that actually runs on a plain macOS dev
# machine, for people (i.e. most Mac users) who don't have the Linux-
# targeting cross toolchains test-tiger64-{riscv64,alpha,arm64,amd64} and
# friends need. Reuses TEST_ARM64_MACHO/TEST_AMD64_MACHO exactly as
# test-all does above, so it stays in sync with ./configure's Darwin
# detection instead of hardcoding the two target names again - on a
# non-Darwin host (no CCARM64MACHO/CCAMD64MACHO in Makefile.config) both
# expand to empty and this target does nothing, matching test-all's own
# behavior for these two tiers.
test-macos:: $(TEST_ARM64_MACHO) $(TEST_AMD64_MACHO)




build-docker:
	docker build -t "cmm" .

