/*s: runtime.c */
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>

#include "qc--runtime.h"
#include "pcmap.h"

/*s: machine-dependent macro definitions for the implementation */
/*s: machine-dependent macro definitions for the implementation ((x86-linux)) */
#define ESP 8 /* r[4] */
#define PC  0 /* c[0] */
/*e: machine-dependent macro definitions for the implementation ((x86-linux)) */
/*e: machine-dependent macro definitions for the implementation */
/*s: external functions */
extern int Cmm_c_change_activation(Cmm_Activation *a);
extern void Cmm_init_c_frame(Cmm_Activation *a, char *young_in_overflow);
/*x: external functions */
int Cmm_is_thread_start_frame(struct cmm_pc_map_entry *rtdata, Cmm_Codeptr pc);
/*x: external functions */
extern void Cmm_start_thread_helper();
extern void Cmm_thread_helper_fence();
extern int Cmm_stack_growth; /* generated by qc-- -globals */
/*e: external functions */
/*s: definitions of private data structures */
struct cmm_activation_methods {
  int (*change)(Cmm_Activation *a);
};
/*e: definitions of private data structures */
/*s: declarations of private functions */
static int normal_change(Cmm_Activation *a);
/*x: declarations of private functions */
void update_saved_regs(Cmm_Activation* new, const Cmm_Activation* prev);
/*x: declarations of private functions */
static Cmm_Word *locptr(const Cmm_Activation *a, location l);
/*x: declarations of private functions */
static void die(char *msg,...);
/*e: declarations of private functions */
/*s: definitions of method suites */
static int change_nothing(Cmm_Activation *a) { return 0; }
static struct cmm_activation_methods cmm_methods    = { normal_change           };
static struct cmm_activation_methods c_methods      = { Cmm_c_change_activation }; 
static struct cmm_activation_methods oldest_methods = { change_nothing          }; 
struct cmm_activation_methods *Cmm_cmm_frame_methods = &cmm_methods;
/*e: definitions of method suites */
/*s: private functions */
static int normal_change(Cmm_Activation *a) {
  char *vfp;
  pc_map_entry* calleedata, *callerdata;

  assert(a && a->vfp);
  calleedata = a->rtdata;

  vfp = a->vfp;
  a->pc      = *(Cmm_Codeptr*)locptr(a, calleedata->return_addressp);
  /* claude: real SPARC "call" hardware stores the call instruction's own
   * address (not +4/+8) into the return register - the same fact
   * Post.return already compensates for via its "jmpl %i7+8" epilogue
   * (see arch/sparc/sparc.ml's `return` comment). But return_addressp
   * hands back that same raw, unadjusted value, and this is a SEPARATE
   * consumer: Cmm_lookup_entry below needs the actual resumption pc
   * (call+8, skipping the call and its delay-slot nop) to match the
   * pcmap table's own keys, which are built from the real continuation
   * label placed after both instructions. Without this, every SPARC
   * frame-walk (tig_gc's root scan, exception unwinding) looked up the
   * wrong pc, got NULL back, and silently treated a live C-- frame as
   * the C/host boundary - skipping its GC roots entirely. Confirmed via
   * gdb: a real qsort.tig run had callee return_addressp = 0x1d69c (the
   * call instruction itself) while the pcmap table's real entry for
   * that call site's continuation was 0x1d6a4 = 0x1d69c + 8. */
#ifdef __sparc__
  a->pc = (Cmm_Codeptr)((char *)a->pc + 8);
#endif
  /* claude: a MIPS-specific mismatch in the opposite direction from
   * sparc's above: here it's the RUNTIME value that's correct and the
   * COMPILER's own pcmap-table key that's wrong. arch/mips's real "jal"
   * hardware sets $31 (ra) to callsite+8 (skipping both the call and its
   * one delay slot) - a fact runtime code reading return_addressp gets
   * "for free," correctly, with no adjustment. But
   * middle/translate/runtimedata.ml's emit_site_spans (target-
   * independent, shared by every backend) keys the pcmap table entry off
   * the raw "call successor" CFG label placed by cfg/zipcfg/zipcfg.ml's
   * `call` (also shared, target-independent) - and on this backend that
   * label lands at callsite+4 (right after the delay-slot nop), one
   * MIPS instruction *before* where $31 actually points, because
   * whatever compiles the call's "successor" block (the result-consuming
   * move, or a placeholder nop when the result is discarded, as for
   * call_gc()) is emitted as ordinary block content *after* the label
   * rather than being accounted for in the label's own placement.
   * Adjusting that label's placement is a target-independent, shared
   * code path this fork wasn't able to isolate a safe local fix in - so,
   * matching the sparc case above (same file, same function, opposite
   * side of the mismatch), compensate at the one point that actually
   * needs the two values to agree: subtract the same 4 bytes back off
   * here so Cmm_lookup_entry's key matches what the table really has.
   * Confirmed via gdb: qsort.tig's tiger_main resumed at 0x4037b4 (real
   * $31, correct) while the pcmap table's actual entry for that call
   * site was keyed at 0x4037b0 = 0x4037b4 - 4. Every non-hello/sieve
   * tiger-mips failure at the time this was found showed the identical
   * "array of size 0" / stale-GC-root symptom family this causes. */
#ifdef __mips__
  a->pc = (Cmm_Codeptr)((char *)a->pc - 4);
#endif
  update_saved_regs(a, a);
  /*s: possibly shout about caller's EBP */
  #define NOISY 0
  #if NOISY
    fprintf(stderr, "leaving C-- activation; caller's EBP == 0x%08x\n",
            a->regs[9] ? (unsigned)*a->regs[9] : 0xdeadbeef);
  #endif
  /*e: possibly shout about caller's EBP */
  callerdata = Cmm_lookup_entry(a->pc);
  a->rtdata  = callerdata;

  if (callerdata) {
    if (Cmm_is_thread_start_frame(callerdata, a->pc))
      return 0;
    /* deallocpt = vfp       + calleedata->inalloc
       deallocpt = callervfp + callerdata->outalloc

       therefore callerfvp = vfp + calleedata->inalloc - callerdata->outalloc 
    */
    a->vfp = vfp + Cmm_as_offset(calleedata->inalloc)
                 - Cmm_as_offset(callerdata->outalloc);
  } else {
    a->methods = &c_methods;
    a->rtdata = Cmm_empty_pcmap_entry;
    Cmm_init_c_frame(a, vfp + Cmm_as_offset(calleedata->inalloc));
  }
  return 1;
}
/*x: private functions */
void update_saved_regs(Cmm_Activation* new, const Cmm_Activation* prev) {
  int i;
  int r = prev->rtdata->num_registers;
  struct reg* regs = registers(prev->rtdata);

  for (i = 0; i < NUM_REGS; i++) 
    new->regs[i] = prev->regs[i];
  
  for (i = 0; i < r; i++)
    new->regs[regs[i].index] = (Cmm_Word*)(prev->vfp + Cmm_as_offset(regs[i].saved));
}
/*x: private functions */
static Cmm_Word *locptr(const Cmm_Activation *a, location l) {
  int reg;
  switch (Cmm_loctype(l)) {
    case REGISTER:
      reg = Cmm_as_register(l);
      assert(a);
      assert(a->regs);
      if (a->regs[reg] == NULL) 
        die("Tried to find a value in an unrecoverable register.\n"
            "Probable cause: calling C without using the \"paranoid C\" convention.");
      return a->regs[reg];
    case DEAD:
      return NULL;
    case OFFSET:
      return (Cmm_Word *)(a->vfp + Cmm_as_offset(l));
    default:
      die("this can't happen --- badly coded location");
      return 0;
  }
}
/*x: private functions */
static void die(char *msg,...) {   /* see K&R 2nd ed, page 174 */
  va_list args;
  va_start(args,msg);
  fprintf(stderr, "C-- run-time error: ");
  vfprintf(stderr, msg, args);
  fprintf(stderr,"\n");
  va_end(args);
  abort();
}
/*e: private functions */
/*s: implementations of public functions */
Cmm_Activation Cmm_YoungestActivation(const Cmm_Cont* k) {
  int i;
  Cmm_Activation a;

  if (k->pc == Cmm_start_thread_helper) {
    a.methods = &oldest_methods;
    a.vfp     = (char *)k->sp;
    a.pc      = k->pc;
    if (Cmm_stack_growth > 0)
      a.rtdata = Cmm_thread_start_up_pcmap_entry;
    else
      a.rtdata = Cmm_thread_start_dn_pcmap_entry;
  } else {
    pc_map_entry* entry = Cmm_lookup_entry(k->pc);
    assert(entry);
    a.methods = &cmm_methods;
    a.vfp     = (char *)k->sp - Cmm_as_offset(entry->outalloc);
    a.pc      = k->pc;
    a.rtdata  = entry;
  }
  for (i = 0; i < NUM_REGS; i++)
    a.regs[i] = NULL;
  return a;
}
/*x: implementations of public functions */
int Cmm_ChangeActivation(Cmm_Activation *a) {
  return a->methods->change(a);
}
/*x: implementations of public functions */
Cmm_Activation Cmm_NextActivation(const Cmm_Activation *a) {
  Cmm_Activation na = *a;
  int rc = na.methods->change(&na);
  assert(rc);
  return na;
}
/*x: implementations of public functions */
int Cmm_isOldestActivation(const Cmm_Activation *a) {
  Cmm_Activation na = *a;
  return (!na.methods->change(&na));
}
/*x: implementations of public functions */
extern void Cmm_unwindcont_pc();  /* assembly code; not a C function */
Cmm_Cont* Cmm_MakeUnwindCont(Cmm_Activation *a, Cmm_Word index, ...) {
  int i;
  struct conts *conts;
  struct contblock *block;

  assert(a->rtdata);
  conts = continuations(a->rtdata);
  if (index >= conts->num_entries)
    die("C-- run-time error: index %d out of bounds in Cmm_MakeUnwindCont", index);
  block = (struct contblock *) ((Cmm_Word *) conts + conts->entries[index]);
  /*s: write variadic parameters into [[block->vars]] */
  {
    va_list ap;
    va_start(ap, index);
    for (i = 0; i < block->num_vars; i++) {
      /*s: assign [[block->vars[i]]] from [[ap]] */
      #define ASSIGN(L,R) \
        { L *formalp = (L*) Cmm_FindLocalVar(a, block->vars[i].localnum); \
          R actual   = va_arg(ap, R); \
          if (formalp) *formalp = (L) actual; \
        } 
      switch(block->vars[i].ctype) {
        case CHAR:             ASSIGN (char,               int);                break;
        case DOUBLE:           ASSIGN (double,             double);             break;
        case FLOAT:            ASSIGN (float,              double);             break;
        case INT:              ASSIGN (int,                int);                break;
        case LONGDOUBLE:       ASSIGN (long double,        long double);        break;
        case LONGINT:          ASSIGN (long int,           long int);           break;
        case LONGLONGINT:      ASSIGN (long long           int, long long int); break;
        case SHORT:            ASSIGN (short,              int);                break;
        case SIGNEDCHAR:       ASSIGN (signed char,        int);                break;
        case UNSIGNEDCHAR:     ASSIGN (unsigned char,      int);                break;
        case UNSIGNEDLONG:     ASSIGN (unsigned long,      unsigned long);      break;
        case UNSIGNEDSHORT:    ASSIGN (unsigned short,     int);                break;
        case UNSIGNEDINT:      ASSIGN (unsigned int,       unsigned int);       break;
        case UNSIGNEDLONGLONG: ASSIGN (unsigned long long, unsigned long long); break;
        case ADDRESS:          ASSIGN (void *,             void *);             break;
        default: assert(0);
      }
      /*e: assign [[block->vars[i]]] from [[ap]] */
      Cmm_LocalVarWritten(a, block->vars[i].localnum);
    }
    va_end(ap);
  }
  /*e: write variadic parameters into [[block->vars]] */

  /* We initialize unknown registers to a bogus (but clearly live) address:
     that of the activation.  Otherwise, assembly code dereferences 0. */
  for (i = 0; i < NUM_REGS; i++)
    if (a->regs[i] == NULL)
      a->regs[i] = (Cmm_Word *)a;

  /* This activation can't be passed into this interface again, so it 
     is safe to overwrite the PC and ESP registers with the values that
     belong to the unwind continuation */

  a->regs[PC]      = (Cmm_Word *) block->pc;
  a->regs[ESP]     = (Cmm_Word *) (a->vfp + Cmm_as_offset(block->sp));
  a->u.unwind.k.pc = Cmm_unwindcont_pc;
  a->u.unwind.k.sp = (Cmm_Word *) a->regs;

  return(&a->u.unwind.k);
}
/*x: implementations of public functions */
Cmm_Dataptr Cmm_GetDescriptor(const Cmm_Activation *a, Cmm_Word token) {
  unsigned num_spans;
  Cmm_Word* descs;
  pc_map_entry* entry = a->rtdata;
  if (!entry)
    return 0;

  num_spans = entry->num_spans;
  if ((unsigned) token < num_spans) {
    descs = spans(entry);
    return (Cmm_Dataptr)descs[token];
  } else {
    return 0;
  }
}
/*x: implementations of public functions */
void Cmm_LocalVarWritten(const Cmm_Activation *a, unsigned n) {
  return;
}
/*x: implementations of public functions */
unsigned Cmm_LocalVarCount(const Cmm_Activation *a) {
  assert(a);
  if (a->rtdata)
    return a->rtdata->num_locals;
  else
    return 0;
}
/*x: implementations of public functions */
void* Cmm_FindLocalVar(const Cmm_Activation *a, unsigned n) {
  pc_map_entry* entry = a->rtdata;
  assert(entry);
  if (n >= entry->num_locals)
    die("local var index %d out of range", n);
  return locptr(a, locals(entry)[n]);
}
/*x: implementations of public functions */
void* Cmm_FindDeadLocalVar(const Cmm_Activation *a, unsigned n) {
  return Cmm_FindLocalVar(a, n);
}
/*x: implementations of public functions */
void* Cmm_FindStackLabel(const Cmm_Activation *a, unsigned n) {
  pc_map_entry* entry = a->rtdata;
  struct sd *sdt = entry->stackdata_table;
  assert(sdt);
  if (n >= sdt->num_entries)
     die("Stack data index %d out of range [0..%d)\n", n, sdt->num_entries);
  return locptr(a, sdt->entries[n]);
}
/*x: implementations of public functions */
int Cmm_is_thread_start_frame(struct cmm_pc_map_entry *rtdata, Cmm_Codeptr pc) {
  return spans(rtdata)[0] == 0xeffaced &&
         (unsigned) Cmm_start_thread_helper <= (unsigned) pc &&
         (unsigned) pc <= (unsigned) Cmm_thread_helper_fence;
}
/*x: implementations of public functions */
Cmm_Cont* Cmm_CreateThread(Cmm_Codeptr f, Cmm_Dataptr x, void *s, unsigned n) {
  char *stack = s;
  char *young, *old, *vfp;
  Cmm_Cont *k;
  if (Cmm_stack_growth < 0) {
    /*s: set up stack for growth downward */
    young = stack;
    old   = stack + n;
    k = (Cmm_Cont *) old;
    k--;
    k->sp = (Cmm_Word*) (vfp = old - sizeof(*k) - sizeof(f) - sizeof(x));
    k->pc = Cmm_start_thread_helper;
    *(Cmm_Codeptr*)vfp = f;
    vfp += sizeof(f);
    *(Cmm_Dataptr*)vfp = x;
    /*e: set up stack for growth downward */
    return k;
  } else {
    /*s: set up stack for growth upward */
    old   = stack;
    young = stack + n;
    k = (Cmm_Cont *) old;
    k++;
    k->sp = (Cmm_Word*) (vfp = old + sizeof(*k) + sizeof(f) + sizeof(x));
    k->pc = Cmm_start_thread_helper;
    *(Cmm_Codeptr*)vfp = f;
    vfp -= sizeof(f);
    *(Cmm_Dataptr*)vfp = x;
    /*e: set up stack for growth upward */
    return k;
  }
}
/*x: implementations of public functions */
static void show_span(unsigned key, void *value, void *closure) {
  if (value)
    printf("    span %d == %p\n", key, value);
}

void Cmm_show_activation(const Cmm_Activation *a) {
  printf("activation @ %p = {\n", (void*)a);
  printf("  methods = ");
  if (a->methods == Cmm_cmm_frame_methods)
    printf("C-- methods,\n");
  else if (a->methods == &c_methods) 
    printf("C methods,\n");
  else
    printf("unknown methods at %p,\n", (void*)a->methods);
  printf("  vfp = %p, pc = %p,\n", a->vfp, (void *)a->pc);
  /*s: print registers in activation [[a]] */
  { int any, i;
    char *pfx;
    any = 0;
    for (i = 0; i < NUM_REGS; i++)
      if (a->regs[i]) {
        any = 1;
        break;
      }
    if (any) {
      printf("  regs = { ");
      pfx = "";
      for (i = 0; i < NUM_REGS; i++)
        if (a->regs[i]) {
          printf("%sREG %d @ %p", pfx, i, (void*)a->regs[i]);
          pfx = ", ";
        }
      printf(" },\n");
    } else {
      printf("  regs = (no registers recoverable),\n");
    }
  }
  /*e: print registers in activation [[a]] */
  printf("  entry = {\n");
  Cmm_show_map_entry(a->rtdata, -1, a->pc, show_span, NULL);
  printf("  }\n}\n");
}
/*e: implementations of public functions */
/*e: runtime.c */
