TOP=../..

SYNCFLAGS=-md5sum_in_auxfile -less_marks -lang ocaml
#SYNCWEBFLAGS=-debug

DOC=Cmm
VERSION=1

# must be in the same order of the #include
SRC_ORIG=Cmm.nw Cmm_extra.nw

#TODO: sync also ast.ml!
#TODO: ir/vfp.ml split from layout/vfprewrite.ml
#TODO: main.ml
#TODO: the arch/xxx/xxx{backend,cc}.ml arch/ppc/ppcelfasm.ml

SRC_VIEWS= \
 $TOP/libs/prelude/auxfuns.mli\
 $TOP/libs/prelude/auxfuns.ml\
 $TOP/libs/prelude/strutil.mli\
 $TOP/libs/prelude/strutil.ml\
 $TOP/libs/prelude/verbose.mli\
 $TOP/libs/prelude/verbose.ml\
 $TOP/libs/prelude/pp.mli\
 $TOP/libs/prelude/pp.ml\
 \
 $TOP/libs/prelude/reinit.mli\
 $TOP/libs/prelude/reinit.ml\
 $TOP/libs/prelude/idgen.mli\
 $TOP/libs/prelude/idgen.ml\
 \
 $TOP/libs/bitops/bits.mli\
 $TOP/libs/bitops/bits.ml\
 $TOP/libs/bitops/bitset64.mli\
 $TOP/libs/bitops/bitset64.ml\
 $TOP/libs/bitops/alignment.mli\
 $TOP/libs/bitops/alignment.ml\
 $TOP/libs/bitops/uint64.mli\
 $TOP/libs/bitops/uint64.ml\
 $TOP/libs/bitops/cell.mli\
 $TOP/libs/bitops/cell.ml\
 $TOP/libs/bitops/ctypes.mli\
 $TOP/libs/bitops/ctypes.ml\
 \
 $TOP/error/debug.mli\
 $TOP/error/debug.ml\
 $TOP/error/error.mli\
 $TOP/error/error.ml\
 $TOP/error/impossible.mli\
 $TOP/error/impossible.ml\
 $TOP/error/srcmap.mli\
 $TOP/error/srcmap.ml\
 $TOP/error/unsupported.mli\
 $TOP/error/unsupported.ml\
 \
 $TOP/ast/astpp.mli\
 $TOP/ast/astpp.ml\
 \
 $TOP/rtl/register.mli\
 $TOP/rtl/register.ml\
 $TOP/rtl/rtl.mli\
 $TOP/rtl/rtl.ml\
 $TOP/rtl/rtldebug.mli\
 $TOP/rtl/rtldebug.ml\
 $TOP/rtl/rtlop.mli\
 $TOP/rtl/rtlop.ml\
 $TOP/rtl/rtlutil.mli\
 $TOP/rtl/rtlutil.ml\
 $TOP/rtl/reloc.mli\
 $TOP/rtl/reloc.ml\
 $TOP/rtl/symbol.mli\
 $TOP/rtl/symbol.ml\
 $TOP/rtl/types.mli\
 $TOP/rtl/types.ml\
 $TOP/rtl/space.mli\
 $TOP/rtl/space.ml\
 \
 $TOP/ir/fenv.mli\
 $TOP/ir/fenv.ml\
 $TOP/ir/asm.mli\
 $TOP/ir/asm.ml\
 $TOP/ir/block.mli\
 $TOP/ir/block.ml\
 $TOP/ir/eqn.mli\
 $TOP/ir/eqn.ml\
 $TOP/ir/metrics.mli\
 $TOP/ir/metrics.ml\
 $TOP/ir/rtleqn.mli\
 $TOP/ir/rtleqn.ml\
 \
 $TOP/ir/context.mli\
 $TOP/ir/context.ml\
 $TOP/ir/talloc.mli\
 $TOP/ir/talloc.ml\
 \
 $TOP/cfg/front_cfg/cfg.mli\
 $TOP/cfg/front_cfg/cfg.ml\
 $TOP/cfg/front_cfg/cfgx.mli\
 $TOP/cfg/front_cfg/cfgx.ml\
 $TOP/cfg/front_cfg/dag.mli\
 $TOP/cfg/front_cfg/dag.ml\
 $TOP/cfg/front_cfg/ep.mli\
 $TOP/cfg/front_cfg/ep.ml\
 $TOP/cfg/front_cfg/mflow.mli\
 $TOP/cfg/front_cfg/mflow.ml\
 $TOP/cfg/front_cfg/spans.mli\
 $TOP/cfg/front_cfg/spans.ml\
 \
 $TOP/cfg/front_zipcfg/zipcfg.mli\
 $TOP/cfg/front_zipcfg/zipcfg.ml\
 $TOP/cfg/front_zipcfg/avail.mli\
 $TOP/cfg/front_zipcfg/avail.ml\
 $TOP/cfg/front_zipcfg/property.mli\
 $TOP/cfg/front_zipcfg/property.ml\
 $TOP/cfg/front_zipcfg/unique.mli\
 $TOP/cfg/front_zipcfg/unique.ml\
 $TOP/cfg/front_zipcfg/varmap.mli\
 $TOP/cfg/front_zipcfg/varmap.ml\
 \
 $TOP/elab/nast.mli\
 $TOP/elab/nast.ml\
 $TOP/elab/nelab.mli\
 $TOP/elab/nelab.ml\
 $TOP/elab/elabexp.mli\
 $TOP/elab/elabexp.ml\
 $TOP/elab/elabstmt.mli\
 $TOP/elab/elabstmt.ml\
 $TOP/elab/memalloc.mli\
 $TOP/elab/memalloc.ml\
 $TOP/elab/simplify.mli\
 $TOP/elab/simplify.ml\
 $TOP/elab/topsort.mli\
 $TOP/elab/topsort.ml\
 \
 $TOP/TODO/callspec.mli\
 $TOP/TODO/callspec.ml\
 \
 $TOP/cfg/dataflow/dataflow.mli\
 $TOP/cfg/dataflow/dataflow.ml\
 $TOP/cfg/dataflow/live.mli\
 $TOP/cfg/dataflow/live.ml\
 $TOP/cfg/dataflow/availpass.mli\
 $TOP/cfg/dataflow/availpass.ml\
 $TOP/cfg/dataflow/dead.mli\
 $TOP/cfg/dataflow/dead.ml\
 $TOP/cfg/dataflow/dominator.mli\
 $TOP/cfg/dataflow/dominator.ml\
 $TOP/cfg/dataflow/tx.mli\
 $TOP/cfg/dataflow/tx.ml\
 \
 $TOP/target/automaton.mli\
 $TOP/target/automaton.ml\
 $TOP/target/automatonutil.mli\
 $TOP/target/automatonutil.ml\
 $TOP/target/box.mli\
 $TOP/target/box.ml\
 $TOP/target/float.mli\
 $TOP/target/float.ml\
 $TOP/target/target.mli\
 $TOP/target/target.ml\
 \
 $TOP/middle/codegen/idcode.mli\
 $TOP/middle/codegen/idcode.ml\
 $TOP/middle/codegen/ast2ir.mli\
 $TOP/middle/codegen/ast2ir.ml\
 $TOP/middle/codegen/automatongraph.mli\
 $TOP/middle/codegen/automatongraph.ml\
 $TOP/middle/codegen/call.mli\
 $TOP/middle/codegen/call.ml\
 $TOP/middle/codegen/contn.mli\
 $TOP/middle/codegen/contn.ml\
 $TOP/middle/codegen/postexpander.mli\
 $TOP/middle/codegen/postexpander.ml\
 $TOP/middle/codegen/expander.mli\
 $TOP/middle/codegen/expander.ml\
 $TOP/middle/codegen/opshape.mli\
 $TOP/middle/codegen/opshape.ml\
 $TOP/middle/codegen/preast2ir.mli\
 $TOP/middle/codegen/preast2ir.ml\
 $TOP/middle/codegen/proc.mli\
 $TOP/middle/codegen/proc.ml\
 $TOP/middle/codegen/rewrite.mli\
 $TOP/middle/codegen/rewrite.ml\
 $TOP/middle/codegen/runtimedata.mli\
 $TOP/middle/codegen/runtimedata.ml\
 \
 $TOP/middle/codegen/widen.mli\
 $TOP/middle/codegen/widen.ml\
 \
 $TOP/middle/layout/mvalidate.mli\
 $TOP/middle/layout/mvalidate.ml\
 $TOP/middle/layout/placevar.mli\
 $TOP/middle/layout/placevar.ml\
 $TOP/middle/layout/vfprewrite.mli\
 $TOP/middle/layout/vfprewrite.ml\
 \
 $TOP/middle/opti/optimize.mli\
 $TOP/middle/opti/optimize.ml\
 $TOP/middle/opti/peephole.mli\
 $TOP/middle/opti/peephole.ml\
 \
 $TOP/backend/asm/astasm.mli\
 $TOP/backend/asm/astasm.ml\
 $TOP/backend/asm/cfgutil.mli\
 $TOP/backend/asm/cfgutil.ml\
 $TOP/backend/asm/dotasm.mli\
 $TOP/backend/asm/dotasm.ml\
 $TOP/backend/asm/dummyasm.mli\
 $TOP/backend/asm/dummyasm.ml\
 $TOP/backend/asm/mangle.mli\
 $TOP/backend/asm/mangle.ml\
 \
 $TOP/backend/regalloc/flowra.mli\
 $TOP/backend/regalloc/flowra.ml\
 $TOP/backend/regalloc/registerclass.mli\
 $TOP/backend/regalloc/registerclass.ml\
 $TOP/backend/regalloc/colorgraph.mli\
 $TOP/backend/regalloc/colorgraph.ml\
 $TOP/backend/regalloc/dls.mli\
 $TOP/backend/regalloc/dls.ml\
 \
 $TOP/arch/dummy/dummy.mli\
 $TOP/arch/dummy/dummy.ml\
 $TOP/arch/dummy/dummyexpander.mlb\
 \
 $TOP/arch/x86/x86.mli\
 $TOP/arch/x86/x86.ml\
 $TOP/arch/x86/x86asm.mli\
 $TOP/arch/x86/x86asm.ml\
 $TOP/arch/x86/x86call.mli\
 $TOP/arch/x86/x86call.ml\
 $TOP/arch/x86/x86rec.mli\
 $TOP/arch/x86/x86rec.mlb\
 $TOP/arch/x86/x86regs.mli\
 $TOP/arch/x86/x86regs.ml\
 \
 $TOP/arch/ppc/ppc.mli\
 $TOP/arch/ppc/ppc.ml\
 $TOP/arch/ppc/ppcasm.mli\
 $TOP/arch/ppc/ppcasm.ml\
 $TOP/arch/ppc/ppcrec.mli\
 $TOP/arch/ppc/ppcrec.mlb\
 \
 $TOP/arch/sparc/sparc.mli\
 $TOP/arch/sparc/sparc.ml\
 $TOP/arch/sparc/sparcasm.mli\
 $TOP/arch/sparc/sparcasm.ml\
 $TOP/arch/sparc/sparccall.mli\
 $TOP/arch/sparc/sparccall.ml\
 $TOP/arch/sparc/sparcrec.mli\
 $TOP/arch/sparc/sparcrec.mlb\
 $TOP/arch/sparc/sparcregs.mli\
 $TOP/arch/sparc/sparcregs.ml\
 \
 $TOP/arch/alpha/alpha.mli\
 $TOP/arch/alpha/alpha.ml\
 $TOP/arch/alpha/alphaasm.mli\
 $TOP/arch/alpha/alphaasm.ml\
 $TOP/arch/alpha/alphacall.mli\
 $TOP/arch/alpha/alphacall.ml\
 $TOP/arch/alpha/alpharec.mli\
 $TOP/arch/alpha/alpharec.mlb\
 \
 $TOP/arch/mips/mips.mli\
 $TOP/arch/mips/mips.ml\
 $TOP/arch/mips/mipsasm.mli\
 $TOP/arch/mips/mipsasm.ml\
 $TOP/arch/mips/mipscall.mli\
 $TOP/arch/mips/mipscall.ml\
 $TOP/arch/mips/mipsrec.mli\
 $TOP/arch/mips/mipsrec.mlb\
 $TOP/arch/mips/mipsregs.mli\
 $TOP/arch/mips/mipsregs.ml\
 \
 $TOP/arch/arm/arm.mli\
 $TOP/arch/arm/arm.ml\
 \
 $TOP/driver/driver.mli\
 $TOP/driver/this.mli\
 $TOP/driver/driver.ml\

#missing: tools/ocamlburg

<$TOP/docs/latex/mkcommon

index:V:
    echo TODO

SYNCFLAGS2=-md5sum_in_auxfile -less_marks -lang C
sync_runtime:VI:
	syncweb $SYNCFLAGS2 $SRC_ORIG $TOP/runtime/qc--runtime.h
	syncweb $SYNCFLAGS2 $SRC_ORIG $TOP/runtime/runtime.c
	syncweb $SYNCFLAGS2 $SRC_ORIG $TOP/runtime/pcmap.h
	syncweb $SYNCFLAGS2 $SRC_ORIG $TOP/runtime/pcmap.c
	syncweb $SYNCFLAGS2 $SRC_ORIG $TOP/runtime/thread.c--
	syncweb $SYNCFLAGS2 $SRC_ORIG $TOP/runtime/cut.c--
	syncweb $SYNCFLAGS2 $SRC_ORIG $TOP/runtime/yield.c--
	syncweb $SYNCFLAGS2 $SRC_ORIG $TOP/runtime/gcc-linux.c
	syncweb $SYNCFLAGS2 $SRC_ORIG $TOP/runtime/x86cont.s
	syncweb $SYNCFLAGS2 $SRC_ORIG $TOP/runtime/pcmap.ld
