TOP=../..

SYNCFLAGS=-md5sum_in_auxfile -less_marks -lang ocaml 
#SYNCWEBFLAGS=-debug

DOC=Cminusminus
VERSION=1

# must be in the same order of the #include
SRC_ORIG=Cminusminus.nw Cminusminus_extra.nw

#TODO: sync also ast.asdl (or ast.ml generated code)

SRC_VIEWS= \
 $TOP/commons/commons2/auxfuns.mli\
 $TOP/commons/commons2/auxfuns.ml\
 $TOP/commons/commons2/lc.mli\
 $TOP/commons/commons2/lc.ml\
 $TOP/commons/commons2/pc.mli\
 $TOP/commons/commons2/pc.ml\
 $TOP/commons/commons2/pc2.mli\
 $TOP/commons/commons2/pc2.ml\
 $TOP/commons/commons2/pp.mli\
 $TOP/commons/commons2/pp.ml\
 $TOP/commons/commons2/rx.mli\
 $TOP/commons/commons2/rx.ml\
 $TOP/commons/commons2/strutil.mli\
 $TOP/commons/commons2/strutil.ml\
 $TOP/commons/commons2/verbose.mli\
 $TOP/commons/commons2/verbose.ml\
 $TOP/commons/commons3/alignment.mli\
 $TOP/commons/commons3/alignment.ml\
 $TOP/commons/commons3/bits.mli\
 $TOP/commons/commons3/bits.ml\
 $TOP/commons/commons3/bitset64.mli\
 $TOP/commons/commons3/bitset64.ml\
 $TOP/commons/commons3/cell.mli\
 $TOP/commons/commons3/cell.ml\
 $TOP/commons/commons3/ctypes.mli\
 $TOP/commons/commons3/ctypes.ml\
 $TOP/commons/commons3/idcode.mli\
 $TOP/commons/commons3/idcode.ml\
 $TOP/commons/commons3/idgen.mli\
 $TOP/commons/commons3/idgen.ml\
 $TOP/commons/commons3/reinit.mli\
 $TOP/commons/commons3/reinit.ml\
 $TOP/commons/commons3/tx.mli\
 $TOP/commons/commons3/tx.ml\
 $TOP/commons/commons3/uint64.mli\
 $TOP/commons/commons3/uint64.ml\
 \
 $TOP/error/debug.mli\
 $TOP/error/debug.ml\
 $TOP/error/error.mli\
 $TOP/error/error.ml\
 $TOP/error/impossible.mli\
 $TOP/error/impossible.ml\
 $TOP/error/srcmap.mli\
 $TOP/error/srcmap.ml\
 $TOP/error/unsupported.mli\
 $TOP/error/unsupported.ml\
 \
 $TOP/ast/astpp.mli\
 $TOP/ast/astpp.ml\
 \
 $TOP/ir/register.mli\
 $TOP/ir/register.ml\
 $TOP/ir/reloc.mli\
 $TOP/ir/reloc.ml\
 $TOP/ir/rtl.mli\
 $TOP/ir/rtl.ml\
 $TOP/ir/rtldebug.mli\
 $TOP/ir/rtldebug.ml\
 $TOP/ir/rtlop.mli\
 $TOP/ir/rtlop.ml\
 $TOP/ir/rtlutil.mli\
 $TOP/ir/rtlutil.ml\
 $TOP/ir/symbol.mli\
 $TOP/ir/symbol.ml\
 $TOP/ir/types.mli\
 $TOP/ir/types.ml\
 $TOP/ir/asm.mli\
 $TOP/ir/asm.ml\
 \
 $TOP/ir/block.mli\
 $TOP/ir/block.ml\
 $TOP/ir/eqn.mli\
 $TOP/ir/eqn.ml\
 $TOP/ir/fenv.mli\
 $TOP/ir/fenv.ml\
 $TOP/ir/metrics.mli\
 $TOP/ir/metrics.ml\
 $TOP/ir/rtleqn.mli\
 $TOP/ir/rtleqn.ml\
 \
 $TOP/cfg/front_cfg/cfg.mli\
 $TOP/cfg/front_cfg/cfg.ml\
 $TOP/cfg/front_cfg/cfgx.mli\
 $TOP/cfg/front_cfg/cfgx.ml\
 $TOP/cfg/front_cfg/dag.mli\
 $TOP/cfg/front_cfg/dag.ml\
 $TOP/cfg/front_cfg/ep.mli\
 $TOP/cfg/front_cfg/ep.ml\
 $TOP/cfg/front_cfg/mflow.mli\
 $TOP/cfg/front_cfg/mflow.ml\
 $TOP/cfg/front_cfg/spans.mli\
 $TOP/cfg/front_cfg/spans.ml\
 \
 $TOP/elab/elabexp.mli\
 $TOP/elab/elabexp.ml\
 $TOP/elab/elabstmt.mli\
 $TOP/elab/elabstmt.ml\
 $TOP/elab/memalloc.mli\
 $TOP/elab/memalloc.ml\
 $TOP/elab/nast.mli\
 $TOP/elab/nast.ml\
 $TOP/elab/nelab.mli\
 $TOP/elab/nelab.ml\
 $TOP/elab/simplify.mli\
 $TOP/elab/simplify.ml\
 $TOP/elab/topsort.mli\
 $TOP/elab/topsort.ml\
 \
 $TOP/target/automaton.mli\
 $TOP/target/automaton.ml\
 $TOP/target/box.mli\
 $TOP/target/box.ml\
 $TOP/target/float.mli\
 $TOP/target/float.ml\
 \
 $TOP/ir/space.mli\
 $TOP/ir/space.ml\
 \
 $TOP/target/target.mli\
 $TOP/target/target.ml\
 \
 $TOP/cfg/front_zipcfg/avail.mli\
 $TOP/cfg/front_zipcfg/avail.ml\
 $TOP/cfg/front_zipcfg/property.mli\
 $TOP/cfg/front_zipcfg/property.ml\
 $TOP/cfg/front_zipcfg/unique.mli\
 $TOP/cfg/front_zipcfg/unique.ml\
 $TOP/cfg/front_zipcfg/varmap.mli\
 $TOP/cfg/front_zipcfg/varmap.ml\
 $TOP/cfg/front_zipcfg/zipcfg.mli\
 $TOP/cfg/front_zipcfg/zipcfg.ml\
 \
 $TOP/codegen/ast2ir.mli\
 $TOP/codegen/ast2ir.ml\
 $TOP/codegen/automatongraph.mli\
 $TOP/codegen/automatongraph.ml\
 $TOP/codegen/call.mli\
 $TOP/codegen/call.ml\
 $TOP/ir/context.mli\
 $TOP/ir/context.ml\
 $TOP/codegen/contn.mli\
 $TOP/codegen/contn.ml\
 $TOP/codegen/postexpander.mli\
 $TOP/codegen/postexpander.ml\
 $TOP/codegen/expander.mli\
 $TOP/codegen/expander.ml\
 $TOP/codegen/opshape.mli\
 $TOP/codegen/opshape.ml\
 $TOP/codegen/preast2ir.mli\
 $TOP/codegen/preast2ir.ml\
 $TOP/codegen/proc.mli\
 $TOP/codegen/proc.ml\
 $TOP/codegen/rewrite.mli\
 $TOP/codegen/rewrite.ml\
 $TOP/codegen/runtimedata.mli\
 $TOP/codegen/runtimedata.ml\
 \
 $TOP/ir/talloc.mli\
 $TOP/ir/talloc.ml\
 \
 $TOP/asm/astasm.mli\
 $TOP/asm/astasm.ml\
 $TOP/asm/cfgutil.mli\
 $TOP/asm/cfgutil.ml\
 $TOP/asm/dotasm.mli\
 $TOP/asm/dotasm.ml\
 $TOP/asm/dummyasm.mli\
 $TOP/asm/dummyasm.ml\
 $TOP/asm/mangle.mli\
 $TOP/asm/mangle.ml\
 \
 $TOP/target/automatonutil.mli\
 $TOP/target/automatonutil.ml\
 $TOP/TODO/arch/callspec.mli\
 $TOP/TODO/arch/callspec.ml\
 $TOP/cfg/dataflow/dataflow.mli\
 $TOP/cfg/dataflow/dataflow.ml\
 $TOP/cfg/dataflow/live.mli\
 $TOP/cfg/dataflow/live.ml\
 \
 $TOP/regalloc/flowra.mli\
 $TOP/regalloc/flowra.ml\
 \
 $TOP/layout/mvalidate.mli\
 $TOP/layout/mvalidate.ml\
 $TOP/layout/placevar.mli\
 $TOP/layout/placevar.ml\
 $TOP/layout/vfp.mli\
 $TOP/layout/vfp.ml\
 \
 $TOP/arch/dummy/dummy.mli\
 $TOP/arch/dummy/dummy.ml\
 $TOP/arch/arm/arm.mli\
 $TOP/arch/arm/arm.ml\
 $TOP/arch/mips/mips.mli\
 $TOP/arch/mips/mips.ml\
 $TOP/arch/mips/mipsasm.mli\
 $TOP/arch/mips/mipsasm.ml\
 $TOP/arch/mips/mipscall.mli\
 $TOP/arch/mips/mipscall.ml\
 $TOP/arch/mips/mipsrec.mli\
 $TOP/arch/mips/mipsregs.mli\
 $TOP/arch/mips/mipsregs.ml\
 $TOP/arch/ppc/ppc.mli\
 $TOP/arch/ppc/ppc.ml\
 $TOP/arch/ppc/ppcasm.mli\
 $TOP/arch/ppc/ppcasm.ml\
 $TOP/arch/ppc/ppcrec.mli\
 $TOP/arch/x86/x86.mli\
 $TOP/arch/x86/x86.ml\
 $TOP/arch/x86/x86asm.mli\
 $TOP/arch/x86/x86asm.ml\
 $TOP/arch/x86/x86call.mli\
 $TOP/arch/x86/x86call.ml\
 $TOP/arch/x86/x86rec.mli\
 $TOP/arch/x86/x86regs.mli\
 $TOP/arch/x86/x86regs.ml\
 \
 $TOP/driver/driver.mli\
 $TOP/driver/this.mli\
 $TOP/driver/driver.ml\

# ./main/main.ml\

#missing: tools/adsl tools/camlburg

<$TOP/docs/latex/mkcommon

index:V:
    echo TODO


SYNCFLAGS2=-md5sum_in_auxfile -less_marks -lang C
sync_runtime:V:
	syncweb $SYNCFLAGS2 $SRC_ORIG $TOP/runtime/qc--runtime.h
	syncweb $SYNCFLAGS2 $SRC_ORIG $TOP/runtime/runtime.c
	syncweb $SYNCFLAGS2 $SRC_ORIG $TOP/runtime/pcmap.h
	syncweb $SYNCFLAGS2 $SRC_ORIG $TOP/runtime/pcmap.c
	syncweb $SYNCFLAGS2 $SRC_ORIG $TOP/runtime/thread.c--
	syncweb $SYNCFLAGS2 $SRC_ORIG $TOP/runtime/cut.c--
	syncweb $SYNCFLAGS2 $SRC_ORIG $TOP/runtime/yield.c--
	syncweb $SYNCFLAGS2 $SRC_ORIG $TOP/runtime/gcc-linux.c
	syncweb $SYNCFLAGS2 $SRC_ORIG $TOP/runtime/x86cont.s
	syncweb $SYNCFLAGS2 $SRC_ORIG $TOP/runtime/pcmap.ld


##docs tests tools todo/... todo/h_lua/ todo/interpreter todo/runtime

#old: when was splitted in many .nw
#NWDIRS= \
#   arch/dummy \
#   arch/mips arch/ppc arch/x86 \
#   assembler \
#   commons2 commons3 \
#   error \
#   front_asm front_cfg front_fenv front_ir front_last front_nelab front_rtl \
#   front_target front_zipcfg \
#   parsing
#
##docs tests tools todo/... todo/h_lua/ todo/interpreter todo/runtime
##h_adsl h_camlburg
#
#synchere:
##	$(SYNCWEB) -lang ocaml main.nw main.ml
#	$(SYNCWEB) -lang ocaml driver.nw driver.mli
#	$(SYNCWEB) -lang ocaml driver.nw driver.ml
#	$(SYNCWEB) -lang ocaml main2.nw this.mli
#	$(SYNCWEB) -lang ocaml main2.nw this.in
#
#sync:
#	set -e; for i in $(NWDIRS); do $(MAKE) -C $$i sync || exit 1; done 
#	make synchere
#
#
#lpdistclean::
#	rm -f $(LPSRC) .md5sum_*
#
#include $(TOP)/docs/latex/Makefile.common
