(include_subdirs unqualified)

(library
 (name cmm_commons)
 (wrapped false)
 (libraries str bigarray unix num)
 (modules
   Common Common_extra Interfaces Objet Ocollection Seti
   Oset Oassoc Osequence Ograph Oarray Ograph_extended
   Ograph_simple Ofullcommon Math Simple_color File_type Glimpse
   Parser_combinators Json_common Sexp_common Ocaml Dumper ANSITerminal
   Set_poly Map_poly SetPt Enum DynArray Suffix_tree
   Suffix_tree_ext Graph_ocamldot Pretty_printer_indent OUnit XML XHTML
   Oseti Oseth Osetb Osetpt Oassocb Oassoch
   Oassoc_buffer Oassoc_cache Oassocid Ograph2way Type Parser
   Lexer Pre_sexp Sexp_intf Sexp Path Conv
   Conv_error Json_type Json_out Netconversion Json_parser Json_lexer
   Json_in Json_io Xml_types Dtd_types Xml_parser Xml_lexer
   XmlParser Dtd Xml_parse Xml_utils
 ))
